#!/usr/bin/env ruby

require 'lib/poker.rb'

def script_main
  tests_flag = false
  input = ""

  ARGV.each do |value|
    tests_flag = true if value == '--tests'
  end

  return show_help unless ARGV.count == 1
  return puts(%x( bundle exec rspec )) if tests_flag

  w = Poker.find_winner( ARGV[0] )
  puts w
end

def show_help
  puts "poker \"input\""
  puts "poker --tests\t\trun tests"
end

script_main
